class Recipe {
  late String name;
  late List<String> ingredients;
  late List<String> steps;
  late int time;
  late double calories;
  late double totalFat;
  late double sugar;
  late double sodium;
  late double protein;
  late double saturatedFat;
  late double carbohydrates;
  Recipe? similar;

  Recipe(
      {required this.name,
      required this.ingredients,
      required this.steps,
      required this.time,
      required this.calories,
      required this.totalFat,
      required this.sugar,
      required this.sodium,
      required this.protein,
      required this.saturatedFat,
      required this.carbohydrates,
      this.similar});
} // CLASS

List<Recipe> recipeSamples = [
  Recipe(
    name: "Brown Sugar Muffins",
    ingredients: [
      'OIL',
      'BROWN SUGAR',
      'EGG',
      'FLOUR',
      'BAKING SODA',
      'SALT',
      'MILK',
      'VANILLA',
      'NUTS'
    ],
    steps: [
      'Step 1: mix together oil, brown sugar, and egg',
      'Step 2: then add flour, soda, salt, milk, and vanilla',
      'Step 3: put into greased muffin tins and bake at 375 for 15-20 minutes',
    ],
    time: 25,
    calories: 244.9,
    totalFat: 16,
    sugar: 71,
    sodium: 9,
    protein: 6,
    saturatedFat: 9,
    carbohydrates: 11,
    similar: Recipe(
      ingredients: [
        'Bananas',
        'Sugar',
        'Egg',
        'Butter',
        'Blueberries',
        'Baking Soda',
        'Baking Powder',
        'Salt',
        'Flour',
      ],
      name: "Easy Moist Banana Blueberry Muffins",
      time: 30,
      steps: [
        'Step 1: Mash bananas in a large mixing bowl.',
        'Step 2: Add sugar and egg and mix well.',
        'Step 3: Add melted butter and blueberries and stir gently to combine.',
        'Step 4: In a separate bowl, combine dry ingredients (baking soda, baking powder, and salt).',
        'Step 5: Gradually add the dry ingredients to the wet ingredients and stir just until combined.',
        'Step 6: Pour batter into 12 well-greased muffin cups.',
        'Step 7: Bake at 375 degrees for 20 minutes or until a toothpick inserted into the center comes out clean.',
        'Step 8: Let cool slightly before serving.',
      ],
      calories: 193.9,
      totalFat: 8.0,
      sugar: 71.0,
      sodium: 11.0,
      protein: 5.0,
      saturatedFat: 17.0,
      carbohydrates: 11.0,
    ),
  ),
  Recipe(
    name: "Tuna Burgers",
    ingredients: [
      'tuna',
      'dry breadcrumbs',
      'celery',
      'mayonnaise',
      'onion',
      'chili sauce',
      'egg',
      'salt',
      'pepper',
      'butter',
      'hamburger buns',
      'lettuce',
      'tomatoes'
    ],
    steps: [
      'Step 1: in a bowl , combine tuna , bread crumbs , celery , mayo , onion , chili sauce , egg , salt and pepper',
      "Step 2: shape into four patties",
      "Step 3: melt butter in a skillet",
      "Step 4: cook patties for about 4-5 minutes per side or until lightly browned",
      'Step 5: serve on buns with lettuce and tomatoes , if desired'
    ],
    time: 15,
    calories: 318.2,
    totalFat: 17,
    sugar: 20,
    sodium: 21,
    protein: 35,
    saturatedFat: 26,
    carbohydrates: 11,
    similar: Recipe(
      ingredients: [
        'Tuna',
        'Mayonnaise',
        'Onion',
        'Green Pepper',
        'Dried Basil',
        'Dried Oregano',
        'Butter',
        'Bread',
        'Cheese',
      ],
      name: "Garden Tuna Melts",
      time: 30,
      steps: [
        'Step 1: In a bowl, mix tuna, mayonnaise, onion, green pepper, dried basil, and dried oregano.',
        'Step 2: Spread the tuna mixture over one slice of bread for each sandwich.',
        'Step 3: Top each with a slice of cheese and another slice of bread.',
        'Step 4: Spread butter on the outsides of each sandwich.',
        'Step 5: Heat a skillet over medium heat.',
        'Step 6: Cook sandwiches for 2-3 minutes per side, or until golden brown and cheese is melted.',
      ],
      calories: 388.6,
      totalFat: 27.0,
      sugar: 11.0,
      sodium: 34.0,
      protein: 50.0,
      saturatedFat: 48.0,
      carbohydrates: 10.0,
    ),
  ),
  Recipe(
    name: "Gingersnap Cookies (Soft & Chewy)",
    ingredients: [
      'flour',
      'baking soda',
      'ground ginger',
      'ground cinnamon',
      'ground cloves',
      'white sugar',
      'margarine',
      'egg',
      'molasses',
      'sugar' // for rolling the dough balls
    ],
    steps: [
      'Step 1: Mix flour, baking soda, ginger, cinnamon, and cloves well. Set aside.',
      'Step 2: In another bowl, use a beater to cream together the sugar, margarine, egg, and molasses for 1-2 minutes.',
      'Step 3: Add the dry ingredients from step 1 to the wet ingredients and mix by hand until just combined.',
      'Step 4: Scoop out dough with a large tablespoon and roll into balls.',
      'Step 5: Place at least 1/4 cup of sugar on a plate.',
      'Step 6: Roll each dough ball in the sugar to coat.',
      'Step 7: Bake on an ungreased cookie sheet at 350°F for 10-12 minutes.',
    ],
    time: 25,
    calories: 169.2,
    totalFat: 12.0,
    sugar: 49.0,
    sodium: 8.0,
    protein: 3.0,
    saturatedFat: 7.0,
    carbohydrates: 7.0,
    similar: Recipe(
      ingredients: [
        'Margarine',
        'White Sugar',
        'Molasses',
        'All-Purpose Flour',
        'Water',
        'Baking Soda',
        'Ground Ginger',
        'Ground Cinnamon',
        'Ground Cloves',
        'Nutmeg',
        'Fresh Ginger',
        'Salt',
        'Raisins',
      ],
      name: "Soft Spicy Heavenly Ginger Cookies",
      time: 25,
      steps: [
        'Step 1: In a large bowl, cream together margarine and 1 cup of sugar until light and fluffy.',
        'Step 2: Stir in the molasses.',
        'Step 3: Mix water and baking soda together, then stir it into the mixture.',
        'Step 4: Sift together flour, salt, and dry spices (ground ginger, cinnamon, cloves, and nutmeg).',
        'Step 5: Gradually add the sifted ingredients to the sugar-margarine mixture.',
        'Step 6: Gradually stir the sifted ingredients, along with the chopped fresh ginger and raisins, into the molasses mixture.',
        'Step 7: Shape dough into walnut-sized balls and roll them in the remaining 2 tablespoons of sugar.',
        'Step 8: Place the cookies 2 inches apart onto an ungreased cookie sheet and flatten slightly.',
        'Step 9: Bake at 350 degrees Fahrenheit for 10-12 minutes.',
        'Step 10: Let cool on a wire rack before serving.',
      ],
      calories: 87.6,
      totalFat: 5.0,
      sugar: 27.0,
      sodium: 4.0,
      protein: 1.0,
      saturatedFat: 3.0,
      carbohydrates: 4.0,
    ),
  ),
  Recipe(
    name: "Crackle Top Molasses Cookies",
    ingredients: [
      'vegetable oil',
      'sugar',
      'egg',
      'molasses',
      'all-purpose flour',
      'baking soda',
      'ground cinnamon',
      'ground ginger',
      'sugar' // for rolling the dough balls
    ],
    steps: [
      'Step 1: Preheat oven to 350°F.',
      'Step 2: In a large bowl, combine oil and 1 cup of sugar.',
      'Step 3: Add the egg and beat well.',
      'Step 4: Stir in molasses, 2 cups of flour, baking soda, cinnamon, and ginger.',
      'Step 5: If necessary, add a little more flour to make a firm dough.',
      'Step 6: Shape the dough into 1 1/4-inch balls.',
      'Step 7: Roll each dough ball in 1/3 cup of sugar.',
      'Step 8: Place the balls 3 inches apart on ungreased baking sheets.',
      'Step 9: Bake for 12 minutes or until golden brown and the tops crack.',
      'Step 10: Cool the cookies on racks.',
    ],
    time: 22,
    calories: 79.0,
    totalFat: 5.0,
    sugar: 27.0,
    sodium: 2.0,
    protein: 1.0,
    saturatedFat: 2.0,
    carbohydrates: 3.0,
    similar: Recipe(
      ingredients: [
        'Creamy Peanut Butter',
        'Butter Flavor Shortening',
        'Brown Sugar',
        'Egg',
        'Half-and-Half',
        'Vanilla',
        'Flour',
        'Baking Soda',
        'Salt',
        'Peanut Butter Chips',
        'Chocolate Chips',
      ],
      name: "The Best Peanut Butter Cookies",
      time: 27,
      steps: [
        'Step 1: Set oven to 350 degrees.',
        'Step 2: In a mixing bowl, cream peanut butter, shortening, and brown sugar.',
        'Step 3: Add egg and mix well.',
        'Step 4: Stir in milk and vanilla.',
        'Step 5: Combine flour, baking soda, and salt.',
        'Step 6: Gradually add the dry ingredients to the creamed mixture.',
        'Step 7: Stir in the peanut butter chips and chocolate chips.',
        'Step 8: Drop by rounded teaspoonfuls onto ungreased baking sheets.',
        'Step 9: Bake for 7-9 minutes or until golden brown.',
        'Step 10: Enjoy!',
      ],
      calories: 81.7,
      totalFat: 6.0,
      sugar: 24.0,
      protein: 3.0,
      saturatedFat: 6.0,
      carbohydrates: 3.0,
      sodium: 2.0,
    ),
  ),
  Recipe(
    ingredients: [
      'CHICKEN',
      'BISQUICK',
      'PAPRIKA',
      'SALT',
      'PEPPER',
      'EGGS',
      'OIL',
      'BUTTER',
      'CHICKEN BROTH',
      'LEMON JUICE',
      'PARSLEY',
      'GARLIC',
      'PASTA'
    ],
    name: "Chicken Francaise",
    time: 50,
    steps: [
      'Step 1: preheat oven to 350 degrees',
      'Step 2: preheat oil in frying pan',
      'Step 3: in a bowl, add bisquick, paprika, salt, and pepper',
      'Step 4: in another bowl, add the 2 eggs',
      'Step 5: dip the chicken in the eggs, then coat with the bisquick mixture',
      'Step 6: brown the chicken in the oil',
      'Step 7: while the chicken is cooking, get a medium-size pot and add the lemon juice, chicken broth, parsley, and butter',
      'Step 8: melt together',
      'Step 9: when chicken is done, place in a deep pan/glass pyrex dish',
      'Step 10: place the chicken in the pan, and pour the sauce over it',
      'Step 11: sprinkle some chopped garlic on the top, and add a splash of the lemon juice',
      'Step 12: cover with foil, and bake for about 30 minutes',
      'Step 13: serve over pasta',
      'Step 14:',
      'Step 15: the sauce will be fairly thin, but we like it that way - feel free to use cornstarch to thicken',
    ],
    calories: 640.4,
    totalFat: 73,
    sugar: 18,
    protein: 40,
    saturatedFat: 108,
    carbohydrates: 7,
    sodium: 40,
    similar: Recipe(
      ingredients: [
        'Chicken Thighs',
        'Garlic Cloves',
        'Salt',
        'Russet Potatoes',
        'Olive Oil',
        'Lemon Juice',
        'Chicken Broth',
      ],
      name: "Amazing Baked Lemon Garlic Chicken Thighs and Potatoes",
      time: 95,
      steps: [
        'Step 1: Preheat oven to 350 degrees Fahrenheit.',
        'Step 2: Remove most of the skin from chicken thighs, leaving a small patch on top.',
        'Step 3: Mince garlic and make a paste with the teaspoon of salt using the side of a large knife. Then, rub the garlic paste all over the tops of the chicken thighs.',
        'Step 4: Peel potatoes and cut them into eight wedges each.',
        'Step 5: Add salt and pepper to the potatoes, drizzle with olive oil, and toss to coat.',
        'Step 6: Sprinkle the chicken thighs with black pepper and place them in a 9x13 inch baking pan.',
        'Step 7: Arrange the potato wedges in and around the chicken thighs.',
        'Step 8: Pour chicken broth into the side of the pan.',
        'Step 9: Sprinkle lemon juice to taste over the top of the dish.',
        'Step 10: Bake at 350 degrees Fahrenheit for about 1 hour and 15 minutes, or until the chicken and potatoes are cooked through.',
        'Step 11: Turn the chicken thighs and potatoes over halfway through cooking time.',
        'Step 12: (Optional) Add more chicken broth during baking if the pan becomes dry.',
      ],
      calories: 669.3,
      totalFat: 45.0,
      sugar: 12.0,
      sodium: 70.0,
      protein: 83.0,
      saturatedFat: 41.0,
      carbohydrates: 19.0,
    ),
  ),
  Recipe(
  ingredients: [
  'KIDNEY BEANS',
  'BLACK BEANS',
  'PINTO BEANS',
  'DICED TOMATOES',
  'CORN',
  'GREEN BELL PEPPER',
  'ONION',
  'GARLIC CLOVES',
  'CHILI POWDER',
  'CUMIN',
  'VEGETABLE BROTH',
  'SALT',
  'PEPPER',
  'OLIVE OIL',
  'OPTIONAL TOPPINGS: CHOPPED AVOCADO, SHREDDED CHEESE, SOUR CREAM',
],

  name: "Spicy Comfort Chili",
  time: 60,
  steps: [
    'Step 1: Rinse and drain the kidney beans, black beans, and pinto beans.',
    'Step 2: Heat olive oil in a large pot or Dutch oven over medium heat.',
    'Step 3: Add chopped onion and green bell pepper, cook until softened, about 5 minutes.',
    'Step 4: Add minced garlic cloves and cook for another minute.',
    'Step 5: Stir in diced tomatoes, chili powder, cumin, salt, and pepper.',
    'Step 6: Add the rinsed and drained beans, and vegetable broth.',
    'Step 7: Bring to a boil, then reduce heat and simmer for 30 minutes, or until slightly thickened.',
    'Step 8: Taste and adjust seasonings as desired.',
    'Step 9: Serve hot with your favorite toppings like chopped avocado, shredded cheese, or sour cream.',
  ],
  calories: 280,  
  totalFat: 10,
  sugar: 15,
  protein: 20,
  saturatedFat: 4,
  carbohydrates: 40,
  sodium: 500, 
)
];
